### ISSUE TITLE
bundle.js 资源已被阻止，因为 MIME 类型不匹配

### ISSUE THREAD

**Issue by ywzhaiqi** [ascoders/run-react#1]
尝试使用 dob-react，引入 run-react 却无法正常工作，提示：

    来自“http://localhost:9091/bundle.js”的资源已被阻止，因为 MIME 类型不匹配（X-Content-Type-Options: nosniff）。

而你的 [dob-example](https://github.com/ascoders/dob-example) 却是正常，不知道为什么？

**Comment by ascoders** [comment]
dob 不支持 ie 的。不过这个问题好像和浏览器兼容性有关，建议看看项目和 example 有什么区别吧？

**Comment by ywzhaiqi** [comment]
感谢回复。是示例里 ts 编译失败，加个 `<any, any>` 就好了

```ts
@Connect
class App extends React.Component<any, any> {
    render() {
        return (
            <span>{this.props.store.name}</span>
        )
    }
}
```
